name: "Upload To Github Release"
description: "Github Action to deploy files to github release"
author: "owent"
inputs:
  file:
    description: "The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files."
    required: true
    default: ""
  delete_file:
    description: "The files or file patterns to delete before uploading new files. You can delete multiple files by split them by semicolon. You can use the glob pattern to find the files."
    required: false
    default: ""
  overwrite:
    description: "If you need to overwrite existing files, add overwrite: true to the with."
    required: false
    default: "false"
  draft:
    description: "The resultant deployment is a draft Release that only repository collaborators can see. This gives you an opportunity to examine and edit the draft release."
    required: false
    default: ""
  prerelease:
    description: "The resultant deployment is a Prerelease. This gives you an opportunity to examine and edit the prerelease."
    required: false
    default: ""
  tags:
    description: "With tags: true, your Releases deployment will trigger if and only if the build is a tagged build."
    required: false
    default: "false"
  branches:
    description: "Only work on these branches(splited by semicolon), set to nothing to accept all branches."
    required: false
    default: ""
  verbose:
    description: "With verbose: true, be verbose."
    required: false
    default: "false"
  tag_name:
    description: "Set custom tag name."
    required: false
    default: ""
  update_latest_release:
    description: "If try to update latest release."
    required: false
    default: "false"
  release_id:
    description: "Set release id to update.If release_id is set, this step will fail if we can not find it."
    required: false
    default: ""
  target_owner:
    description: "Set the owner of target repository(default: current user/origanization)."
    required: false
    default: ""
  target_repo:
    description: "Set target repository(default: current repository)."
    required: false
    default: ""

outputs:
  release_id:
    description: "The release id"
  release_name:
    description: "The release name"
  release_url:
    description: "The release url"
  release_tag_name:
    description: "The release tag name"
  release_commitish:
    description: "The release commit"

runs:
  using: "node16"
  main: "lib/index.js"

# env:
#   key: value

branding:
  icon: "upload"
  color: "gray-dark"
