name: NPM Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Publish to npm"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          set -e
          if [ -n "$NPM_AUTH_TOKEN" ]; then
            # Respect NPM_CONFIG_USERCONFIG if it is provided, default to $HOME/.npmrc
            NPM_CONFIG_USERCONFIG="${NPM_CONFIG_USERCONFIG-"$HOME/.npmrc"}"
            NPM_REGISTRY_URL="${NPM_REGISTRY_URL-registry.npmjs.org}"
            NPM_STRICT_SSL="${NPM_STRICT_SSL-true}"
            NPM_REGISTRY_SCHEME="https"
            if ! $NPM_STRICT_SSL
            then
              NPM_REGISTRY_SCHEME="http"
            fi

            # Allow registry.npmjs.org to be overridden with an environment variable
            printf "//%s/:_authToken=%s\\nregistry=%s\\nstrict-ssl=%s" "$NPM_REGISTRY_URL" "$NPM_AUTH_TOKEN" "${NPM_REGISTRY_SCHEME}://$NPM_REGISTRY_URL" "${NPM_STRICT_SSL}" > "$NPM_CONFIG_USERCONFIG" ;

            chmod 600 "$NPM_CONFIG_USERCONFIG" ;
          fi

          npm publish ;
